<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Naudotojai extends \App\Entity\Naudotojai implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'naudotojo_vardas', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'vardas', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'pavarde', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'el_pastas', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'asmens_kodas', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'telefono_nr', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'role', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'uzblokuotas', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'slaptazodis', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'nekilnojamasTurtas'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'naudotojo_vardas', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'vardas', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'pavarde', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'el_pastas', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'asmens_kodas', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'telefono_nr', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'role', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'uzblokuotas', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'slaptazodis', '' . "\0" . 'App\\Entity\\Naudotojai' . "\0" . 'nekilnojamasTurtas'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Naudotojai $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNaudotojoVardas(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaudotojoVardas', []);

        return parent::getNaudotojoVardas();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaudotojoVardas(string $naudotojo_vardas): \App\Entity\Naudotojai
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaudotojoVardas', [$naudotojo_vardas]);

        return parent::setNaudotojoVardas($naudotojo_vardas);
    }

    /**
     * {@inheritDoc}
     */
    public function getVardas(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVardas', []);

        return parent::getVardas();
    }

    /**
     * {@inheritDoc}
     */
    public function setVardas(string $vardas): \App\Entity\Naudotojai
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVardas', [$vardas]);

        return parent::setVardas($vardas);
    }

    /**
     * {@inheritDoc}
     */
    public function getPavarde(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPavarde', []);

        return parent::getPavarde();
    }

    /**
     * {@inheritDoc}
     */
    public function setPavarde(string $pavarde): \App\Entity\Naudotojai
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPavarde', [$pavarde]);

        return parent::setPavarde($pavarde);
    }

    /**
     * {@inheritDoc}
     */
    public function getElPastas(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getElPastas', []);

        return parent::getElPastas();
    }

    /**
     * {@inheritDoc}
     */
    public function setElPastas(string $el_pastas): \App\Entity\Naudotojai
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setElPastas', [$el_pastas]);

        return parent::setElPastas($el_pastas);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsmensKodas(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsmensKodas', []);

        return parent::getAsmensKodas();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsmensKodas(int $asmens_kodas): \App\Entity\Naudotojai
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsmensKodas', [$asmens_kodas]);

        return parent::setAsmensKodas($asmens_kodas);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoNr(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoNr', []);

        return parent::getTelefonoNr();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoNr(string $telefono_nr): \App\Entity\Naudotojai
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoNr', [$telefono_nr]);

        return parent::setTelefonoNr($telefono_nr);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', []);

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole(string $role): \App\Entity\Naudotojai
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', [$role]);

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getUzblokuotas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUzblokuotas', []);

        return parent::getUzblokuotas();
    }

    /**
     * {@inheritDoc}
     */
    public function addUzblokuota(\App\Entity\Blokavimai $uzblokuota): \App\Entity\Naudotojai
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUzblokuota', [$uzblokuota]);

        return parent::addUzblokuota($uzblokuota);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUzblokuota(\App\Entity\Blokavimai $uzblokuota): \App\Entity\Naudotojai
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUzblokuota', [$uzblokuota]);

        return parent::removeUzblokuota($uzblokuota);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlaptazodis(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlaptazodis', []);

        return parent::getSlaptazodis();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlaptazodis(string $slaptazodis): \App\Entity\Naudotojai
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlaptazodis', [$slaptazodis]);

        return parent::setSlaptazodis($slaptazodis);
    }

    /**
     * {@inheritDoc}
     */
    public function getNekilnojamasTurtas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNekilnojamasTurtas', []);

        return parent::getNekilnojamasTurtas();
    }

    /**
     * {@inheritDoc}
     */
    public function addNekilnojamasTurtas(\App\Entity\NekilnojamasTurtas $nekilnojamasTurtas): \App\Entity\Naudotojai
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNekilnojamasTurtas', [$nekilnojamasTurtas]);

        return parent::addNekilnojamasTurtas($nekilnojamasTurtas);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNekilnojamasTurtas(\App\Entity\NekilnojamasTurtas $nekilnojamasTurtas): \App\Entity\Naudotojai
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNekilnojamasTurtas', [$nekilnojamasTurtas]);

        return parent::removeNekilnojamasTurtas($nekilnojamasTurtas);
    }

}
