<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2yhvv9\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2yhvv9/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX2yhvv9.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX2yhvv9\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerX2yhvv9\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'X2yhvv9',
    'container.build_id' => '2aeff4de',
    'container.build_time' => 1544281896,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2yhvv9');
