<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMO5vi6S\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMO5vi6S/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMO5vi6S.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMO5vi6S\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMO5vi6S\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MO5vi6S',
    'container.build_id' => '01ba49cc',
    'container.build_time' => 1543575550,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMO5vi6S');
