<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJeLYH7X\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJeLYH7X/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJeLYH7X.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJeLYH7X\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJeLYH7X\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JeLYH7X',
    'container.build_id' => '8a3ac5b3',
    'container.build_time' => 1544974808,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJeLYH7X');
